### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Shaquu**
My edit is to add hint for UniFi users in terms of troubles and timeouts.

Story:

Even if the mi device is stored on a European server, it looks like some connections are proxied through China servers.
In my case, I had to disable Country Restriction in my UniFi - actually, I just allowed outgoing for the time when I was fetching tokens.

UniFi Country Restriction

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
To be exact: logging in is handled using China servers, devices are retrieved from different ones

**Comment by PiotrMachowski** [comment]
Thanks, @Shaquu!

**Comment by Shaquu** [comment]
Wow, welcome 🤣

**Comment by PiotrMachowski** [comment]
@Shaquu I have started my "spring cleaning" on GitHub 😄

**Pull request merged**
