### PR TITLE
Add shared houses support

### LINKED ISSUE #65: No support for second houses / shared houses
In my xiaomi app I have two houses. The device I was searching for is in the second house. However, the script does not find it. I moved the device in the first house device group, and it worked. So maybe there is a way to check in all houses in this script.

### PR DESCRIPTION
**Pull request by roncapat**
Fixes #65
Moreover, it lets the user import the class from another scripts and adds a static method useful to decrypt data with nonce obtained from packet dumps.

I used "Packet Capture" Android App to get to the solution. I am able to reverse a big part of the REST API now since I've built myself a script to do so: if other features are needed I can dig into the decrypted logs to identify endpoints/params.

### CODE REVIEW

**Comment by PiotrMachowski** [comment]
Nice work! 👍

**Comment by Rittsel** [comment]
This didn't initially work for me because device_info returned None. Changed line 292 to the following fixed it.

`if devices["result"]["device_info"] is None or len(devices["result"]["device_info"]) == 0:`

**Comment by roncapat** [comment]
Any news for merging?

**Comment by PiotrMachowski** [comment]
Thanks, @roncapat!

**Pull request merged**
