### PR TITLE
Run script using docker

### PR DESCRIPTION
**Pull request by JakobPetersson**
For those who do not have a reasonable python 3 environment.

### CODE REVIEW

**Comment by mikaellindemann** [comment]
A small suggestion would be to add a .dockerignore file to only copy relevant files into the context. E.g. the windows binary is not needed and could be ignored.

**Comment by JakobPetersson** [comment]
> A small suggestion would be to add a .dockerignore file to only copy relevant files into the context. E.g. the windows binary is not needed and could be ignored.

Only `requirements.txt` and `token_extractor.py` is copied into the docker image.

**Comment by mikaellindemann** [comment]
That is true.
But when you run `docker build`, everything not ignored is transferred to dockers build context. This also means that if you change the Readme or the Windows binary, docker cannot use the previously cached layers.

**Comment by JakobPetersson** [comment]
> That is true.
> But when you run `docker build`, everything not ignored is transferred to dockers build context. This also means that if you change the Readme or the Windows binary, docker cannot use the previously cached layers.

Thank you!
I amended the PR.

**Comment by PiotrMachowski** [comment]
Nice idea, thanks!

**Pull request merged**
